### ISSUE TITLE
Error 500 firelet

### ISSUE THREAD

**Issue by paayalav1987** [FedericoCeratto/firelet#2]
Hello, help me!!!!:
and he raised firelet but now I get this error:

firelet@firelet:~$ sudo fireletd -c /var/lib/firelet/firelet.ini
[sudo] password for firelet:
/usr/local/lib/python2.7/dist-packages/firelet-0.5.0a4dev-py2.7.egg/firelet/flut                                                                                        ils.py:37: UserWarning: hmac.compare_digest is missing, using workaround.
2016-05-12 11:41:03 [2682] INFO root (success) Firelet started.
2016-05-12 11:41:03 [2682] INFO root (main) Configuration loaded.
2016-05-12 11:41:03 [2682] INFO root (main) 1 users, 0 hosts, 1 rules, 1 network                                                                                        s loaded.
serving on http://10.27.51.113:8083
2016-05-12 11:41:23 [2682] ERROR root (__init__) Internal error 'None':
  Output: File does not exist.
  Header: None
  None --- End of traceback ---
None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 856, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 1721, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3511, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3483, in template
    TEMPLATES[tplid] = adapter(name=tpl, lookup=lookup, **settings)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3112, in __init__
    raise TemplateError('Template %s not found.' % repr(name))
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3082, in __init__
    HTTPError.__init__(self, 500, message)
TypeError: unbound method __init__() must be called with LoggedHTTPError instance as first argument (got TemplateError instance instead)
2016-05-12 11:41:37 [2682] ERROR root (__init__) Internal error 'unbound method __init__() must be called with LoggedHTTPError instance as first argument (got TemplateError instance instead)':
  Output: Internal Server Error
  Header: None
  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 856, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 1721, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3511, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3483, in template
    TEMPLATES[tplid] = adapter(name=tpl, lookup=lookup, **settings)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3112, in __init__
    raise TemplateError('Template %s not found.' % repr(name))
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3082, in __init__
    HTTPError.__init__(self, 500, message)
TypeError: unbound method __init__() must be called with LoggedHTTPError instance as first argument (got TemplateError instance instead)
 --- End of traceback ---
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 856, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 1721, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3511, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3483, in template
    TEMPLATES[tplid] = adapter(name=tpl, lookup=lookup, **settings)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3112, in __init__
    raise TemplateError('Template %s not found.' % repr(name))
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 3082, in __init__
    HTTPError.__init__(self, 500, message)
TypeError: unbound method __init__() must be called with LoggedHTTPError instance as first argument (got TemplateError instance instead)

**Comment by FedericoCeratto** [comment]
@paayalav1987 the daemon needs to be started from the directory where the Bottle templates are installed. See for example the RUNPATH variable in https://github.com/FedericoCeratto/firelet/blob/master/extras/firelet.init.d
You might want to use an initscript instead of launching the daemon manually.

**Comment by paayalav1987** [comment]
Federico, you realize support or give advice to firelet?

Enviado desde mi iPhone
